-- Fresh Phase-Prefixed Supabase Foundation
--
-- Creates the shared local PostgreSQL schema that becomes the single source of truth for
-- Terra Space and the four n8n workflows. See:
--   project-knowledge/decisions/Fresh-Phase-Prefixed-Supabase-Architecture.md
--   project-knowledge/plans/2026-08-10-fresh-supabase-foundation.md
--
-- Safety rules honoured by this file:
--   * It only creates new objects. It never drops, truncates, renames, or deletes an existing
--     table, column, or row.
--   * Every new table name carries a literal phase1_ / phase2_ / phase3_ prefix, except
--     app_settings, which genuinely serves every phase.
--   * Every statement is written to be safe to run twice.
--
-- Sections:
--   1. Shared helper (updated_at trigger function)
--   2. Phase 1 tables - collect and clean sources
--   3. Phase 2 tables - detect event candidates
--   4. Phase 3 reference tables - event types, taxonomy, actors, locations, gazetteer
--   5. Phase 3 authoritative event tables and relationships
--   6. Application-wide settings
--   7. Indexes
--   8. updated_at triggers
--   9. Authority function: phase3_create_pipeline_event
--  10. Row Level Security
--  11. Plain-language table and column comments


-- =====================================================================================
-- 1. Shared helper
-- =====================================================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function public.set_updated_at() is
  'Trigger helper. Stamps updated_at with the current time whenever a row is changed.';


-- =====================================================================================
-- 2. Phase 1 - collect and clean sources
-- =====================================================================================

create table if not exists public.phase1_sources (
  id                      uuid primary key default gen_random_uuid(),
  sequence_id             bigint generated by default as identity unique,
  title                   text not null,
  publication_date        text not null,
  raw_content_text        text not null,
  cleaned_content_text    text,
  source_domain           text not null,
  source_url              text not null,
  author                  text not null,
  collection_source       text not null,
  processing_status       text not null default 'draft'
                            constraint phase1_sources_processing_status_check
                            check (processing_status in (
                              'draft', 'queued', 'processing', 'ready_for_review', 'completed', 'failed'
                            )),
  processing_error        text,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create table if not exists public.phase1_attachments (
  id                uuid primary key default gen_random_uuid(),
  phase1_source_id  uuid not null references public.phase1_sources (id) on delete cascade,
  relative_path     text not null unique,
  original_name     text not null,
  media_type        text not null,
  size_bytes        bigint not null
                      constraint phase1_attachments_size_bytes_check check (size_bytes >= 0),
  checksum          text not null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create table if not exists public.phase1_processing_runs (
  run_id                    bigint generated by default as identity primary key,
  phase1_source_id          uuid references public.phase1_sources (id) on delete set null,
  submission_key            uuid not null,
  outcome                   text not null
                              constraint phase1_processing_runs_outcome_check
                              check (outcome in ('SUCCESS', 'FAILED')),
  model_name                text,
  prompt_version            text,
  cleaned_character_count   integer
                              constraint phase1_processing_runs_cleaned_character_count_check
                              check (cleaned_character_count is null or cleaned_character_count >= 0),
  raw_output                text,
  error_message             text,
  processed_at              timestamptz not null default now()
);


-- =====================================================================================
-- 3. Phase 2 - detect event candidates
-- =====================================================================================

create table if not exists public.phase2_event_candidates (
  id                            uuid primary key default gen_random_uuid(),
  phase1_source_id              uuid not null unique
                                  references public.phase1_sources (id) on delete cascade,
  main_issue_status             text not null
                                  constraint phase2_event_candidates_main_issue_status_check
                                  check (main_issue_status in ('MAIN_ISSUE_FOUND', 'NO_MAIN_ISSUE', 'FAILED')),
  main_issue                    jsonb,
  event_detection_status        text not null
                                  constraint phase2_event_candidates_event_detection_status_check
                                  check (event_detection_status in (
                                    'EVENT_CANDIDATES_FOUND', 'NO_EVENT_CANDIDATE', 'NOT_RUN', 'FAILED'
                                  )),
  event_candidates              jsonb not null default '[]'::jsonb
                                  constraint phase2_event_candidates_event_candidates_is_array
                                  check (jsonb_typeof(event_candidates) = 'array'),
  model_name                    text not null,
  prompt_version                text not null,
  main_issue_raw_output         text,
  event_detection_raw_output    text,
  error_message                 text,
  processed_at                  timestamptz not null,
  created_at                    timestamptz not null default now(),
  updated_at                    timestamptz not null default now()
);

create table if not exists public.phase2_candidate_runs (
  run_id                        bigint generated by default as identity primary key,
  phase1_source_id              uuid not null references public.phase1_sources (id) on delete cascade,
  main_issue_status             text not null
                                  constraint phase2_candidate_runs_main_issue_status_check
                                  check (main_issue_status in ('MAIN_ISSUE_FOUND', 'NO_MAIN_ISSUE', 'FAILED')),
  main_issue                    jsonb,
  event_detection_status        text not null
                                  constraint phase2_candidate_runs_event_detection_status_check
                                  check (event_detection_status in (
                                    'EVENT_CANDIDATES_FOUND', 'NO_EVENT_CANDIDATE', 'NOT_RUN', 'FAILED'
                                  )),
  event_candidates              jsonb not null default '[]'::jsonb
                                  constraint phase2_candidate_runs_event_candidates_is_array
                                  check (jsonb_typeof(event_candidates) = 'array'),
  model_name                    text not null,
  prompt_version                text not null,
  main_issue_raw_output         text,
  event_detection_raw_output    text,
  error_message                 text,
  processed_at                  timestamptz not null,
  created_at                    timestamptz not null default now()
);


-- =====================================================================================
-- 4. Phase 3 reference tables
-- =====================================================================================

create table if not exists public.phase3_event_types (
  id           uuid primary key default gen_random_uuid(),
  name         text not null unique,
  description  text not null,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table if not exists public.phase3_taxonomy_nodes (
  id             uuid primary key default gen_random_uuid(),
  name           text not null,
  description    text,
  level          text not null
                   constraint phase3_taxonomy_nodes_level_check
                   check (level in ('domain', 'category', 'subcategory', 'event_type')),
  parent_id      uuid references public.phase3_taxonomy_nodes (id) on delete restrict,
  event_type_id  uuid unique references public.phase3_event_types (id) on delete set null,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint phase3_taxonomy_nodes_domain_is_root
    check ((level = 'domain') = (parent_id is null)),
  constraint phase3_taxonomy_nodes_only_leaf_carries_event_type
    check (level = 'event_type' or event_type_id is null)
);

-- Sibling names must be unique. Two indexes are needed because domains have no parent and
-- PostgreSQL treats each NULL parent_id as distinct inside a plain unique constraint.
create unique index if not exists phase3_taxonomy_nodes_unique_child_name
  on public.phase3_taxonomy_nodes (parent_id, lower(name))
  where parent_id is not null;

create unique index if not exists phase3_taxonomy_nodes_unique_domain_name
  on public.phase3_taxonomy_nodes (lower(name))
  where parent_id is null;

create table if not exists public.phase3_actors (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.phase3_actor_aliases (
  id          uuid primary key default gen_random_uuid(),
  actor_id    uuid not null references public.phase3_actors (id) on delete cascade,
  alias       text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint phase3_actor_aliases_unique_alias unique (actor_id, alias)
);

create table if not exists public.phase3_locations (
  id                    uuid primary key default gen_random_uuid(),
  country_iso3          text
                          constraint phase3_locations_country_iso3_check
                          check (country_iso3 is null or country_iso3 ~ '^[A-Z]{3}$'),
  admin1                text,
  city_regency          text,
  latitude              numeric(9,6)
                          constraint phase3_locations_latitude_check
                          check (latitude is null or (latitude >= -90 and latitude <= 90)),
  longitude             numeric(9,6)
                          constraint phase3_locations_longitude_check
                          check (longitude is null or (longitude >= -180 and longitude <= 180)),
  coordinate_precision  text
                          constraint phase3_locations_coordinate_precision_check
                          check (coordinate_precision is null
                                 or coordinate_precision in ('country', 'admin1', 'city_regency')),
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- One row per distinct place, so events can share locations instead of duplicating them.
create unique index if not exists phase3_locations_unique_place
  on public.phase3_locations (
    coalesce(country_iso3, ''),
    coalesce(lower(admin1), ''),
    coalesce(lower(city_regency), '')
  );

create table if not exists public.phase3_location_gazetteer (
  lookup_key            text primary key,
  country_iso3          text not null
                          constraint phase3_location_gazetteer_country_iso3_check
                          check (country_iso3 ~ '^[A-Z]{3}$'),
  admin1                text,
  city_regency          text,
  latitude              numeric(9,6) not null
                          constraint phase3_location_gazetteer_latitude_check
                          check (latitude >= -90 and latitude <= 90),
  longitude             numeric(9,6) not null
                          constraint phase3_location_gazetteer_longitude_check
                          check (longitude >= -180 and longitude <= 180),
  coordinate_precision  text not null
                          constraint phase3_location_gazetteer_coordinate_precision_check
                          check (coordinate_precision in ('country', 'admin1', 'city_regency'))
);


-- =====================================================================================
-- 5. Phase 3 authoritative events and relationships
-- =====================================================================================

create table if not exists public.phase3_events (
  id                        uuid primary key default gen_random_uuid(),
  candidate_key             text unique,
  phase1_source_id          uuid references public.phase1_sources (id) on delete restrict,
  origin                    text not null
                              constraint phase3_events_origin_check
                              check (origin in ('pipeline', 'manual')),
  pipeline_outcome          text
                              constraint phase3_events_pipeline_outcome_check
                              check (pipeline_outcome is null or pipeline_outcome in ('FINAL', 'EXCEPTION')),
  dashboard_status          text not null default 'published'
                              constraint phase3_events_dashboard_status_check
                              check (dashboard_status in (
                                'published', 'hidden', 'rejected', 'archived', 'merged'
                              )),
  title                     text not null,
  summary                   text not null,
  event_date                text,
  event_date_precision      text
                              constraint phase3_events_event_date_precision_check
                              check (event_date_precision is null
                                     or event_date_precision in ('exact', 'month', 'year', 'unknown')),
  epistemic_status          text not null
                              constraint phase3_events_epistemic_status_check
                              check (epistemic_status in (
                                'confirmed', 'reported', 'alleged', 'planned', 'denied', 'unknown'
                              )),
  event_type_id             uuid references public.phase3_event_types (id) on delete set null,
  pipeline_candidate        jsonb,
  pipeline_event_snapshot   jsonb,
  pipeline_first_seen_at    timestamptz,
  human_modified_at         timestamptz,
  human_modified_fields     jsonb not null default '[]'::jsonb
                              constraint phase3_events_human_modified_fields_is_array
                              check (jsonb_typeof(human_modified_fields) = 'array'),
  published_at              timestamptz,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),
  constraint phase3_events_pipeline_requires_candidate_key
    check (origin <> 'pipeline' or candidate_key is not null),
  constraint phase3_events_pipeline_requires_outcome
    check (origin <> 'pipeline' or pipeline_outcome is not null),
  constraint phase3_events_pipeline_requires_source
    check (origin <> 'pipeline' or phase1_source_id is not null),
  constraint phase3_events_manual_has_no_pipeline_outcome
    check (origin <> 'manual' or pipeline_outcome is null)
);

create table if not exists public.phase3_event_runs (
  run_id                bigint generated by default as identity primary key,
  candidate_key         text not null,
  phase1_source_id      uuid not null references public.phase1_sources (id) on delete restrict,
  attempt_number        integer not null
                          constraint phase3_event_runs_attempt_number_check
                          check (attempt_number in (1, 2)),
  candidate             jsonb not null,
  factual_status        text,
  event_record          jsonb,
  taxonomy_status       text,
  safeguard_status      text,
  safeguard_reasons     jsonb,
  factual_raw_output    text,
  taxonomy_raw_output   text,
  safeguard_raw_output  text,
  error_message         text,
  processed_at          timestamptz not null,
  outcome_payload       jsonb not null,
  created_at            timestamptz not null default now()
);

create table if not exists public.phase3_event_sources (
  event_id          uuid not null references public.phase3_events (id) on delete cascade,
  phase1_source_id  uuid not null references public.phase1_sources (id) on delete restrict,
  reference_label   text not null,
  evidence_quote    text,
  created_at        timestamptz not null default now(),
  primary key (event_id, phase1_source_id)
);

create table if not exists public.phase3_event_actors (
  event_id    uuid not null references public.phase3_events (id) on delete cascade,
  actor_id    uuid not null references public.phase3_actors (id) on delete restrict,
  role        text not null
                constraint phase3_event_actors_role_check check (role in ('source', 'target')),
  created_at  timestamptz not null default now(),
  primary key (event_id, actor_id, role)
);

create table if not exists public.phase3_event_locations (
  event_id     uuid not null references public.phase3_events (id) on delete cascade,
  location_id  uuid not null references public.phase3_locations (id) on delete restrict,
  created_at   timestamptz not null default now(),
  primary key (event_id, location_id)
);

create table if not exists public.phase3_duplicate_flags (
  id                uuid primary key default gen_random_uuid(),
  event_id          uuid not null references public.phase3_events (id) on delete cascade,
  matched_event_id  uuid not null references public.phase3_events (id) on delete restrict,
  matched_reason    text not null,
  resolution        text not null default 'pending'
                      constraint phase3_duplicate_flags_resolution_check
                      check (resolution in ('pending', 'kept_separate', 'linked')),
  resolved_at       timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint phase3_duplicate_flags_not_self check (event_id <> matched_event_id),
  constraint phase3_duplicate_flags_unique_pair unique (event_id, matched_event_id)
);


-- =====================================================================================
-- 6. Application-wide settings
-- =====================================================================================

create table if not exists public.app_settings (
  id                                    text primary key default 'default'
                                          constraint app_settings_single_row_check check (id = 'default'),
  lm_studio_base_url                    text,
  lm_studio_model                       text,
  lm_studio_extraction_timeout_seconds  integer not null default 300
                                          constraint app_settings_timeout_check
                                          check (lm_studio_extraction_timeout_seconds > 0),
  created_at                            timestamptz not null default now(),
  updated_at                            timestamptz not null default now()
);

insert into public.app_settings (id)
values ('default')
on conflict (id) do nothing;


-- =====================================================================================
-- 7. Indexes
-- =====================================================================================

-- Phase 1
create index if not exists phase1_sources_processing_status_idx
  on public.phase1_sources (processing_status);
create index if not exists phase1_sources_created_at_idx
  on public.phase1_sources (created_at desc);
create index if not exists phase1_attachments_source_idx
  on public.phase1_attachments (phase1_source_id);
create index if not exists phase1_processing_runs_source_processed_idx
  on public.phase1_processing_runs (phase1_source_id, processed_at desc);
create index if not exists phase1_processing_runs_submission_key_idx
  on public.phase1_processing_runs (submission_key);

-- Phase 2
create index if not exists phase2_event_candidates_processed_at_idx
  on public.phase2_event_candidates (processed_at desc);
create index if not exists phase2_candidate_runs_source_processed_idx
  on public.phase2_candidate_runs (phase1_source_id, processed_at desc);

-- Phase 3 reference
create index if not exists phase3_taxonomy_nodes_parent_idx
  on public.phase3_taxonomy_nodes (parent_id);
create index if not exists phase3_taxonomy_nodes_level_idx
  on public.phase3_taxonomy_nodes (level);
create index if not exists phase3_event_types_active_idx
  on public.phase3_event_types (is_active);
create index if not exists phase3_actor_aliases_actor_idx
  on public.phase3_actor_aliases (actor_id);

-- Phase 3 events: the columns the Dashboard filters and sorts on
create index if not exists phase3_events_dashboard_status_idx
  on public.phase3_events (dashboard_status);
create index if not exists phase3_events_status_event_date_idx
  on public.phase3_events (dashboard_status, event_date);
create index if not exists phase3_events_event_type_idx
  on public.phase3_events (event_type_id);
create index if not exists phase3_events_created_at_idx
  on public.phase3_events (created_at desc);
create index if not exists phase3_events_published_at_idx
  on public.phase3_events (published_at desc);
create index if not exists phase3_events_source_idx
  on public.phase3_events (phase1_source_id);

-- Phase 3 relationships and history
create index if not exists phase3_event_actors_actor_idx
  on public.phase3_event_actors (actor_id);
create index if not exists phase3_event_locations_location_idx
  on public.phase3_event_locations (location_id);
create index if not exists phase3_event_sources_source_idx
  on public.phase3_event_sources (phase1_source_id);
create index if not exists phase3_event_runs_source_processed_idx
  on public.phase3_event_runs (phase1_source_id, processed_at desc);
create index if not exists phase3_event_runs_candidate_attempt_idx
  on public.phase3_event_runs (candidate_key, attempt_number);
create index if not exists phase3_duplicate_flags_event_idx
  on public.phase3_duplicate_flags (event_id);
create index if not exists phase3_duplicate_flags_matched_event_idx
  on public.phase3_duplicate_flags (matched_event_id);
create index if not exists phase3_duplicate_flags_resolution_idx
  on public.phase3_duplicate_flags (resolution);


-- =====================================================================================
-- 8. updated_at triggers
-- =====================================================================================

create or replace trigger phase1_sources_set_updated_at
  before update on public.phase1_sources
  for each row execute function public.set_updated_at();

create or replace trigger phase1_attachments_set_updated_at
  before update on public.phase1_attachments
  for each row execute function public.set_updated_at();

create or replace trigger phase2_event_candidates_set_updated_at
  before update on public.phase2_event_candidates
  for each row execute function public.set_updated_at();

create or replace trigger phase3_event_types_set_updated_at
  before update on public.phase3_event_types
  for each row execute function public.set_updated_at();

create or replace trigger phase3_taxonomy_nodes_set_updated_at
  before update on public.phase3_taxonomy_nodes
  for each row execute function public.set_updated_at();

create or replace trigger phase3_actors_set_updated_at
  before update on public.phase3_actors
  for each row execute function public.set_updated_at();

create or replace trigger phase3_actor_aliases_set_updated_at
  before update on public.phase3_actor_aliases
  for each row execute function public.set_updated_at();

create or replace trigger phase3_locations_set_updated_at
  before update on public.phase3_locations
  for each row execute function public.set_updated_at();

create or replace trigger phase3_events_set_updated_at
  before update on public.phase3_events
  for each row execute function public.set_updated_at();

create or replace trigger phase3_duplicate_flags_set_updated_at
  before update on public.phase3_duplicate_flags
  for each row execute function public.set_updated_at();

create or replace trigger app_settings_set_updated_at
  before update on public.app_settings
  for each row execute function public.set_updated_at();


-- =====================================================================================
-- 9. Authority function: phase3_create_pipeline_event
-- =====================================================================================
--
-- This is the ONLY way the n8n pipeline is allowed to create an authoritative event.
-- It exists so that the rules from the approved architecture live in the database itself
-- rather than in workflow nodes that are easy to change by accident:
--
--   * A missing candidate key or Phase 1 source is rejected outright.
--   * A candidate key that already has an event returns that event's id and changes nothing.
--     A later pipeline run may add audit history, but may never overwrite the authoritative
--     event and may never touch the owner's edits.
--   * FINAL becomes a published event; EXCEPTION becomes a hidden one.
--   * The complete candidate JSON and the complete Phase 3 event JSON are stored as-is.
--   * Sources, actors and locations are linked only when the event is newly created.
--   * human_modified_at and human_modified_fields are never written here.
--
-- Expected payload shape (unknown or unusable values are stored as blank, never guessed):
--
--   {
--     "candidate_key":        "text, required",
--     "phase1_source_id":     "uuid, required",
--     "pipeline_outcome":     "FINAL | EXCEPTION, required",
--     "title":                "text (falls back to candidate.working_title)",
--     "summary":              "text (falls back to candidate.summary)",
--     "event_date":           "text, optional",
--     "event_date_precision": "exact | month | year | unknown, optional",
--     "epistemic_status":     "confirmed | reported | alleged | planned | denied | unknown",
--     "event_type_id":        "uuid, optional",
--     "event_type_name":      "text, optional - matched against active event types only",
--     "processed_at":         "timestamptz, optional (defaults to now)",
--     "reference_label":      "text, optional",
--     "evidence_quote":       "text, optional",
--     "candidate":            { ...full Phase 2 candidate... },
--     "event_snapshot":       { ...full Phase 3 event record... },
--     "actors":               [ { "name": "text", "role": "source" | "target" } ],
--     "locations":            [ { "country_iso3": "UKR", "admin1": null,
--                                 "city_regency": "kharkiv", "latitude": 0, "longitude": 0,
--                                 "coordinate_precision": "city_regency" } ]
--   }

create or replace function public.phase3_create_pipeline_event(payload jsonb)
returns uuid
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_candidate_key  text;
  v_source_text    text;
  v_source_id      uuid;
  v_outcome        text;
  v_status         text;
  v_title          text;
  v_summary        text;
  v_epistemic      text;
  v_precision      text;
  v_event_type_id  uuid;
  v_type_text      text;
  v_processed_text text;
  v_processed_at   timestamptz;
  v_event_id       uuid;
  v_candidate      jsonb;
  v_snapshot       jsonb;
  v_actors         jsonb;
  v_locations      jsonb;
  v_actor          jsonb;
  v_actor_id       uuid;
  v_actor_name     text;
  v_actor_role     text;
  v_location       jsonb;
  v_location_id    uuid;
  v_country        text;
  v_admin1         text;
  v_city           text;
  v_latitude       numeric;
  v_longitude      numeric;
  v_coord_prec     text;
begin
  if payload is null or jsonb_typeof(payload) <> 'object' then
    raise exception 'phase3_create_pipeline_event: payload must be a JSON object.'
      using errcode = '22023';
  end if;

  -- ---- required identity -------------------------------------------------------------
  v_candidate_key := nullif(btrim(coalesce(payload ->> 'candidate_key', '')), '');
  if v_candidate_key is null then
    raise exception 'phase3_create_pipeline_event: candidate_key is required.'
      using errcode = '22023';
  end if;

  v_source_text := nullif(btrim(coalesce(payload ->> 'phase1_source_id', '')), '');
  if v_source_text is null then
    raise exception 'phase3_create_pipeline_event: phase1_source_id is required.'
      using errcode = '22023';
  end if;
  begin
    v_source_id := v_source_text::uuid;
  exception
    when invalid_text_representation then
      raise exception 'phase3_create_pipeline_event: phase1_source_id "%" is not a valid UUID.',
        v_source_text using errcode = '22023';
  end;

  if not exists (select 1 from public.phase1_sources where id = v_source_id) then
    raise exception 'phase3_create_pipeline_event: Phase 1 source % does not exist.', v_source_id
      using errcode = '23503';
  end if;

  v_outcome := upper(btrim(coalesce(payload ->> 'pipeline_outcome', '')));
  if v_outcome not in ('FINAL', 'EXCEPTION') then
    raise exception 'phase3_create_pipeline_event: pipeline_outcome must be FINAL or EXCEPTION, got "%".',
      coalesce(payload ->> 'pipeline_outcome', '') using errcode = '22023';
  end if;

  -- ---- already authoritative: return it untouched --------------------------------------
  select id into v_event_id
    from public.phase3_events
   where candidate_key = v_candidate_key;
  if v_event_id is not null then
    return v_event_id;
  end if;

  -- ---- normalise the rest of the payload ------------------------------------------------
  v_candidate := case when jsonb_typeof(payload -> 'candidate') = 'object'
                      then payload -> 'candidate' else null end;
  v_snapshot  := case when jsonb_typeof(payload -> 'event_snapshot') = 'object'
                      then payload -> 'event_snapshot' else null end;

  v_title := coalesce(
    nullif(btrim(coalesce(payload ->> 'title', '')), ''),
    nullif(btrim(coalesce(v_candidate ->> 'working_title', '')), '')
  );
  if v_title is null then
    raise exception 'phase3_create_pipeline_event: a title is required (payload.title or candidate.working_title).'
      using errcode = '22023';
  end if;

  v_summary := coalesce(
    nullif(btrim(coalesce(payload ->> 'summary', '')), ''),
    nullif(btrim(coalesce(v_candidate ->> 'summary', '')), '')
  );
  if v_summary is null then
    raise exception 'phase3_create_pipeline_event: a summary is required (payload.summary or candidate.summary).'
      using errcode = '22023';
  end if;

  -- Pipeline epistemic values arrive in upper case. Anything unrecognised becomes
  -- "unknown" rather than a guess.
  v_epistemic := lower(btrim(coalesce(payload ->> 'epistemic_status', '')));
  if v_epistemic not in ('confirmed', 'reported', 'alleged', 'planned', 'denied', 'unknown') then
    v_epistemic := 'unknown';
  end if;

  v_precision := lower(btrim(coalesce(payload ->> 'event_date_precision', '')));
  if v_precision not in ('exact', 'month', 'year', 'unknown') then
    v_precision := null;
  end if;

  -- Closed taxonomy: match an ACTIVE event type or leave the type blank. Never create one.
  v_event_type_id := null;
  v_type_text := nullif(btrim(coalesce(payload ->> 'event_type_id', '')), '');
  if v_type_text is not null then
    begin
      select id into v_event_type_id
        from public.phase3_event_types
       where id = v_type_text::uuid and is_active;
    exception
      when invalid_text_representation then
        v_event_type_id := null;
    end;
  end if;
  if v_event_type_id is null then
    v_type_text := nullif(btrim(coalesce(payload ->> 'event_type_name', '')), '');
    if v_type_text is not null then
      select id into v_event_type_id
        from public.phase3_event_types
       where is_active and lower(btrim(name)) = lower(v_type_text)
       limit 1;
    end if;
  end if;

  v_processed_text := nullif(btrim(coalesce(payload ->> 'processed_at', '')), '');
  begin
    v_processed_at := coalesce(v_processed_text::timestamptz, now());
  exception
    when others then
      v_processed_at := now();
  end;

  v_status := case v_outcome when 'FINAL' then 'published' else 'hidden' end;

  -- ---- create the authoritative event ---------------------------------------------------
  insert into public.phase3_events (
    candidate_key, phase1_source_id, origin, pipeline_outcome, dashboard_status,
    title, summary, event_date, event_date_precision, epistemic_status, event_type_id,
    pipeline_candidate, pipeline_event_snapshot, pipeline_first_seen_at, published_at
  )
  values (
    v_candidate_key, v_source_id, 'pipeline', v_outcome, v_status,
    v_title, v_summary,
    nullif(btrim(coalesce(payload ->> 'event_date', '')), ''),
    v_precision, v_epistemic, v_event_type_id,
    v_candidate, v_snapshot, v_processed_at,
    case when v_status = 'published' then v_processed_at else null end
  )
  on conflict (candidate_key) do nothing
  returning id into v_event_id;

  if v_event_id is null then
    -- Another call created the same candidate key first. Return that one unchanged.
    select id into v_event_id
      from public.phase3_events
     where candidate_key = v_candidate_key;
    return v_event_id;
  end if;

  -- ---- link the Phase 1 source and its evidence -----------------------------------------
  insert into public.phase3_event_sources (event_id, phase1_source_id, reference_label, evidence_quote)
  values (
    v_event_id,
    v_source_id,
    coalesce(nullif(btrim(coalesce(payload ->> 'reference_label', '')), ''), 'Phase 1 source'),
    nullif(btrim(coalesce(payload ->> 'evidence_quote', '')), '')
  )
  on conflict do nothing;

  -- ---- actors ----------------------------------------------------------------------------
  v_actors := case when jsonb_typeof(payload -> 'actors') = 'array'
                   then payload -> 'actors' else '[]'::jsonb end;
  for v_actor in select value from jsonb_array_elements(v_actors)
  loop
    continue when jsonb_typeof(v_actor) <> 'object';
    v_actor_name := nullif(btrim(coalesce(v_actor ->> 'name', '')), '');
    v_actor_role := lower(btrim(coalesce(v_actor ->> 'role', '')));
    continue when v_actor_name is null or v_actor_role not in ('source', 'target');

    insert into public.phase3_actors (name) values (v_actor_name)
    on conflict (name) do nothing;

    select id into v_actor_id from public.phase3_actors where name = v_actor_name;

    insert into public.phase3_event_actors (event_id, actor_id, role)
    values (v_event_id, v_actor_id, v_actor_role)
    on conflict do nothing;
  end loop;

  -- ---- locations --------------------------------------------------------------------------
  v_locations := case when jsonb_typeof(payload -> 'locations') = 'array'
                      then payload -> 'locations' else '[]'::jsonb end;
  for v_location in select value from jsonb_array_elements(v_locations)
  loop
    continue when jsonb_typeof(v_location) <> 'object';

    v_country := upper(nullif(btrim(coalesce(v_location ->> 'country_iso3', '')), ''));
    if v_country is not null and v_country !~ '^[A-Z]{3}$' then
      v_country := null;
    end if;
    v_admin1 := nullif(btrim(coalesce(v_location ->> 'admin1', '')), '');
    v_city   := nullif(btrim(coalesce(v_location ->> 'city_regency', '')), '');
    continue when v_country is null and v_admin1 is null and v_city is null;

    v_latitude := case when coalesce(v_location ->> 'latitude', '') ~ '^-?[0-9]+(\.[0-9]+)?$'
                       then (v_location ->> 'latitude')::numeric else null end;
    v_longitude := case when coalesce(v_location ->> 'longitude', '') ~ '^-?[0-9]+(\.[0-9]+)?$'
                        then (v_location ->> 'longitude')::numeric else null end;
    if v_latitude is null or v_longitude is null
       or v_latitude < -90 or v_latitude > 90
       or v_longitude < -180 or v_longitude > 180 then
      v_latitude := null;
      v_longitude := null;
    end if;

    v_coord_prec := lower(btrim(coalesce(v_location ->> 'coordinate_precision', '')));
    if v_coord_prec not in ('country', 'admin1', 'city_regency') then
      v_coord_prec := null;
    end if;

    select id into v_location_id
      from public.phase3_locations
     where coalesce(country_iso3, '') = coalesce(v_country, '')
       and coalesce(lower(admin1), '') = coalesce(lower(v_admin1), '')
       and coalesce(lower(city_regency), '') = coalesce(lower(v_city), '');

    if v_location_id is null then
      insert into public.phase3_locations (
        country_iso3, admin1, city_regency, latitude, longitude, coordinate_precision
      )
      values (v_country, v_admin1, v_city, v_latitude, v_longitude, v_coord_prec)
      returning id into v_location_id;
    end if;

    insert into public.phase3_event_locations (event_id, location_id)
    values (v_event_id, v_location_id)
    on conflict do nothing;
  end loop;

  return v_event_id;
end;
$$;

comment on function public.phase3_create_pipeline_event(jsonb) is
  'The only way the n8n pipeline may create an authoritative Phase 3 event. FINAL becomes a published event, EXCEPTION becomes a hidden one. Calling it again with the same candidate key returns the existing event and changes nothing, so a rerun can never overwrite the event or the owner''s edits.';

revoke all on function public.phase3_create_pipeline_event(jsonb) from public;
grant execute on function public.phase3_create_pipeline_event(jsonb) to service_role;


-- =====================================================================================
-- 10. Row Level Security
-- =====================================================================================
--
-- Every new table has RLS turned on and no policies at all. The service role used by the
-- backend and by n8n bypasses RLS, so the local system keeps working; the browser-facing
-- anon and authenticated keys match no policy and therefore see nothing. This keeps
-- source text, events, and settings away from any browser client.

alter table public.phase1_sources             enable row level security;
alter table public.phase1_attachments         enable row level security;
alter table public.phase1_processing_runs     enable row level security;
alter table public.phase2_event_candidates    enable row level security;
alter table public.phase2_candidate_runs      enable row level security;
alter table public.phase3_event_types         enable row level security;
alter table public.phase3_taxonomy_nodes      enable row level security;
alter table public.phase3_actors              enable row level security;
alter table public.phase3_actor_aliases       enable row level security;
alter table public.phase3_locations           enable row level security;
alter table public.phase3_location_gazetteer  enable row level security;
alter table public.phase3_events              enable row level security;
alter table public.phase3_event_runs          enable row level security;
alter table public.phase3_event_sources       enable row level security;
alter table public.phase3_event_actors        enable row level security;
alter table public.phase3_event_locations     enable row level security;
alter table public.phase3_duplicate_flags     enable row level security;
alter table public.app_settings               enable row level security;

-- Supabase hands the browser-facing anon and authenticated roles a SELECT grant on every
-- new table in the public schema by default. RLS already blocks the rows, but the grant
-- alone still leaks the table and column names through the auto-generated GraphQL schema.
-- Nothing in Terra Space uses those two roles, so take the grant away entirely.
do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'phase1_sources', 'phase1_attachments', 'phase1_processing_runs',
    'phase2_event_candidates', 'phase2_candidate_runs',
    'phase3_event_types', 'phase3_taxonomy_nodes', 'phase3_actors', 'phase3_actor_aliases',
    'phase3_locations', 'phase3_location_gazetteer',
    'phase3_events', 'phase3_event_runs', 'phase3_event_sources', 'phase3_event_actors',
    'phase3_event_locations', 'phase3_duplicate_flags',
    'app_settings'
  ] loop
    execute format('revoke all on table public.%I from anon, authenticated', v_table);
  end loop;
end;
$$;


-- =====================================================================================
-- 11. Plain-language table and column comments
-- =====================================================================================

-- ---- Phase 1 -------------------------------------------------------------------------
comment on table public.phase1_sources is
  'Phase 1. One collected source article: where it came from, its original text, and the cleaned text the later phases read.';
comment on column public.phase1_sources.id is
  'Permanent identifier for this source. Phase 2 and Phase 3 rows point back here.';
comment on column public.phase1_sources.sequence_id is
  'Simple counting number showing the order sources were collected. Convenient for humans; never used as a link.';
comment on column public.phase1_sources.publication_date is
  'The date the source itself says it was published, kept as plain text exactly as reported.';
comment on column public.phase1_sources.raw_content_text is
  'The article text exactly as it was collected, before any cleaning.';
comment on column public.phase1_sources.cleaned_content_text is
  'The cleaned article text. Every quote used as evidence later must appear here word for word. Blank until cleaning succeeds.';
comment on column public.phase1_sources.collection_source is
  'How this article arrived, for example a manual form entry or an automated collector.';
comment on column public.phase1_sources.processing_status is
  'Where this source is in the workflow: draft, queued, processing, ready_for_review, completed, or failed.';
comment on column public.phase1_sources.processing_error is
  'Plain-language reason the last processing attempt failed. Blank when nothing failed.';

comment on table public.phase1_attachments is
  'Phase 1. Details of files attached to a source. The files themselves stay on this computer; only their location is recorded here.';
comment on column public.phase1_attachments.relative_path is
  'Where the file sits inside the local attachments folder. Unique, so one file is never recorded twice.';
comment on column public.phase1_attachments.checksum is
  'Fingerprint of the file contents, used to notice if a file changed or was replaced.';

comment on table public.phase1_processing_runs is
  'Phase 1. Append-only history of every cleaning attempt. Rows are added, never edited, so a failure stays visible.';
comment on column public.phase1_processing_runs.submission_key is
  'Identifies one submission attempt, so a retry of the same article can be told apart from a new article.';
comment on column public.phase1_processing_runs.outcome is
  'SUCCESS or FAILED for this single attempt.';
comment on column public.phase1_processing_runs.raw_output is
  'Exactly what the local AI returned for this attempt, kept unchanged for troubleshooting.';
comment on column public.phase1_processing_runs.error_message is
  'Plain-language reason this attempt failed. Blank on success.';

-- ---- Phase 2 -------------------------------------------------------------------------
comment on table public.phase2_event_candidates is
  'Phase 2. The latest candidate-detection result for each Phase 1 source: one row per source, replaced each time it is re-run.';
comment on column public.phase2_event_candidates.phase1_source_id is
  'The Phase 1 source these candidates came from. One row per source.';
comment on column public.phase2_event_candidates.main_issue_status is
  'Whether a main issue was found: MAIN_ISSUE_FOUND, NO_MAIN_ISSUE, or FAILED. NO_MAIN_ISSUE is a normal, successful answer.';
comment on column public.phase2_event_candidates.main_issue is
  'The detected main issue and its supporting quote, stored exactly as produced.';
comment on column public.phase2_event_candidates.event_detection_status is
  'Result of candidate detection: EVENT_CANDIDATES_FOUND, NO_EVENT_CANDIDATE, NOT_RUN (skipped because there was no main issue), or FAILED.';
comment on column public.phase2_event_candidates.event_candidates is
  'The list of grounded candidate events. Always a JSON array; an empty array means none were found.';
comment on column public.phase2_event_candidates.main_issue_raw_output is
  'Exactly what the local AI returned for the main-issue step, kept unchanged for troubleshooting.';
comment on column public.phase2_event_candidates.event_detection_raw_output is
  'Exactly what the local AI returned for the candidate step, kept unchanged for troubleshooting.';
comment on column public.phase2_event_candidates.processed_at is
  'When this result was produced.';

comment on table public.phase2_candidate_runs is
  'Phase 2. Append-only history of every candidate-detection run, kept so repeat runs can be compared. Rows are added, never edited.';
comment on column public.phase2_candidate_runs.processed_at is
  'When this particular run was produced.';

-- ---- Phase 3 reference ----------------------------------------------------------------
comment on table public.phase3_event_types is
  'Phase 3. The closed list of Event Types that may be assigned to an event. Local AI may pick an active one or leave the type blank; it may never invent one.';
comment on column public.phase3_event_types.description is
  'Plain-language meaning of this Event Type. It is shown to the local AI so it can choose correctly.';
comment on column public.phase3_event_types.is_active is
  'True when this type may be assigned right now. Deactivating hides it from new work without deleting history.';

comment on table public.phase3_taxonomy_nodes is
  'Phase 3. The four-level taxonomy tree: Domain, then Category, then Subcategory, then Event Type. Only the Event Type leaf can be attached to an event.';
comment on column public.phase3_taxonomy_nodes.level is
  'Which level this node sits at: domain, category, subcategory, or event_type.';
comment on column public.phase3_taxonomy_nodes.parent_id is
  'The node one level up. Only a domain has no parent.';
comment on column public.phase3_taxonomy_nodes.event_type_id is
  'The Event Type this leaf represents. Only a node at the event_type level may have one.';
comment on column public.phase3_taxonomy_nodes.is_active is
  'True when this branch is in use. Deactivating keeps the structure and history intact.';

comment on table public.phase3_actors is
  'Phase 3. Reusable actors - the people, organisations, or countries that events involve.';
comment on table public.phase3_actor_aliases is
  'Phase 3. Other names the same actor is known by, so differently worded sources still match one actor.';

comment on table public.phase3_locations is
  'Phase 3. Normalised places used by events, with coordinates when they could be resolved locally.';
comment on column public.phase3_locations.country_iso3 is
  'Three-letter uppercase country code, for example UKR. Blank when no country was grounded in the source.';
comment on column public.phase3_locations.admin1 is
  'First-level area inside the country, such as a province, oblast, or state.';
comment on column public.phase3_locations.city_regency is
  'City or regency level place name.';
comment on column public.phase3_locations.latitude is
  'Latitude found by local lookup only. Blank when the place could not be resolved; it is never guessed.';
comment on column public.phase3_locations.longitude is
  'Longitude found by local lookup only. Blank when the place could not be resolved; it is never guessed.';
comment on column public.phase3_locations.coordinate_precision is
  'How exact the coordinates are: country, admin1, or city_regency.';

comment on table public.phase3_location_gazetteer is
  'Phase 3. Offline lookup table of place names and their coordinates. Used to resolve locations on this computer, with no internet request.';
comment on column public.phase3_location_gazetteer.lookup_key is
  'The exact text used to find a place: the country code alone, or the country code, a unit-separator character, and the place name in lower case.';
comment on column public.phase3_location_gazetteer.country_iso3 is
  'Three-letter uppercase country code taken from the lookup key.';
comment on column public.phase3_location_gazetteer.admin1 is
  'The area name from the lookup key, when this row describes an admin1 area.';
comment on column public.phase3_location_gazetteer.city_regency is
  'The place name from the lookup key, when this row describes a city or regency.';
comment on column public.phase3_location_gazetteer.coordinate_precision is
  'Which level this row resolves: country, admin1, or city_regency.';

-- ---- Phase 3 events -------------------------------------------------------------------
comment on table public.phase3_events is
  'Phase 3. The authoritative event records. Everything Terra Insight shows - Dashboard, Events, map, timeline, filters - reads this table and nothing else.';
comment on column public.phase3_events.candidate_key is
  'Stable fingerprint of the candidate this event came from. Unique, so the same candidate can never create a second event. Blank for events added by hand.';
comment on column public.phase3_events.phase1_source_id is
  'The Phase 1 source this event was derived from, so every event can be traced back to real text.';
comment on column public.phase3_events.origin is
  'Where this event came from: pipeline (created automatically) or manual (added by the owner).';
comment on column public.phase3_events.pipeline_outcome is
  'The automatic result: FINAL means the checks accepted it, EXCEPTION means they did not. Blank for events added by hand.';
comment on column public.phase3_events.dashboard_status is
  'What the owner sees: published (visible in Terra Insight), hidden (kept as an exception), rejected (hidden by the owner), archived (set aside but recoverable), or merged.';
comment on column public.phase3_events.event_date is
  'When the event happened, as far as the source states it. Blank when the source does not say; it is never guessed.';
comment on column public.phase3_events.event_date_precision is
  'How exact the date is: exact, month, year, or unknown.';
comment on column public.phase3_events.epistemic_status is
  'How certain the claim is: confirmed, reported, alleged, planned, denied, or unknown. Uncertainty stays visible instead of being smoothed away.';
comment on column public.phase3_events.pipeline_candidate is
  'The complete Phase 2 candidate this event came from, stored exactly as it was.';
comment on column public.phase3_events.pipeline_event_snapshot is
  'The complete Phase 3 record the pipeline produced, stored exactly as it was, so the original automatic result survives later edits.';
comment on column public.phase3_events.pipeline_first_seen_at is
  'When the pipeline first created this event.';
comment on column public.phase3_events.human_modified_at is
  'When the owner last changed this event by hand. Blank means the owner has never edited it. The pipeline never writes this.';
comment on column public.phase3_events.human_modified_fields is
  'List of field names the owner has edited by hand. These are the owner''s decisions and always take precedence over a later pipeline run.';
comment on column public.phase3_events.published_at is
  'When this event became visible in Terra Insight. Blank while it is not published.';

comment on table public.phase3_event_runs is
  'Phase 3. Append-only history of every processing attempt, including the one allowed retry, and why a candidate was accepted or rejected. Rows are added, never edited.';
comment on column public.phase3_event_runs.candidate_key is
  'The candidate this attempt was about. It matches the candidate key on the authoritative event when one was created.';
comment on column public.phase3_event_runs.attempt_number is
  'Which attempt this was: 1 for the first try, 2 for the single allowed retry.';
comment on column public.phase3_event_runs.candidate is
  'The Phase 2 candidate exactly as it was fed into this attempt.';
comment on column public.phase3_event_runs.event_record is
  'The enriched event this attempt produced. Blank when the attempt failed before producing one.';
comment on column public.phase3_event_runs.factual_status is
  'Result of the factual-enrichment step for this attempt.';
comment on column public.phase3_event_runs.taxonomy_status is
  'Result of matching this candidate against the closed Event Type list.';
comment on column public.phase3_event_runs.safeguard_status is
  'Result of the independent second check that reads only the article: ACCEPT or REJECT.';
comment on column public.phase3_event_runs.safeguard_reasons is
  'The reasons the independent check gave, kept so a rejection can be understood.';
comment on column public.phase3_event_runs.outcome_payload is
  'The full outcome of this attempt in one place, kept unchanged for auditing.';

comment on table public.phase3_event_sources is
  'Phase 3. Links each event to the Phase 1 sources it came from, together with the exact quote that supports it.';
comment on column public.phase3_event_sources.reference_label is
  'Short human-readable label for this source, shown next to the event.';
comment on column public.phase3_event_sources.evidence_quote is
  'The exact words from the cleaned source text that support this event.';

comment on table public.phase3_event_actors is
  'Phase 3. Links events to actors and records whether the actor acted (source) or was acted upon (target).';
comment on column public.phase3_event_actors.role is
  'source when this actor did the thing, target when it was done to them.';

comment on table public.phase3_event_locations is
  'Phase 3. Links events to the places they happened. One event may have several places.';

comment on table public.phase3_duplicate_flags is
  'Phase 3. Possible duplicate events found by the system, and the owner''s decision about each. Nothing is ever merged automatically.';
comment on column public.phase3_duplicate_flags.matched_reason is
  'Plain-language reason these two events look like the same thing.';
comment on column public.phase3_duplicate_flags.resolution is
  'The owner''s decision: pending, kept_separate, or linked.';

-- ---- Application-wide ------------------------------------------------------------------
comment on table public.app_settings is
  'Settings that serve the whole system rather than one phase. Holds exactly one row, with the id "default".';
comment on column public.app_settings.id is
  'Always the text "default". The check constraint keeps this table to a single row.';
comment on column public.app_settings.lm_studio_base_url is
  'Web address of the local LM Studio server. Blank means the built-in default is used.';
comment on column public.app_settings.lm_studio_model is
  'Name of the local model to use. Blank means whichever model LM Studio has loaded.';
comment on column public.app_settings.lm_studio_extraction_timeout_seconds is
  'How many seconds to wait for the local AI before giving up.';
